## Change these first
owner: cilukbaDev # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Demo
    url: https://demo.opensourcepos.org
  - name: Dev
    url: https://dev.opensourcepos.org
  - name: Weblate
    url: https://translate.opensourcepos.org
 

status-website:

  cname: status.kreasiindo.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Deployment page uptime monitor"
  introMessage: This page shows **real-time** deploy stats for our test and dev servers.
  navbar:
    - title: Status
      href: kreasiindo.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
